bridges = []
persistence_dir = ''

[[agents]]
id = 'hc-run-agent'
keystore_file = 'Bob'
name = 'Bob'
public_address = 'HcSCi6q54V833PVHd9mckeY33vCHeymwm7wnkM5UwKGnbijrC38eV3FOqqmb7za'
test_agent = true

[[dnas]]
file = 'dist/cc_tuts.dna.json'
hash = 'Qma9vfkeU5UCchV89D44PAjDd4quVi7CddJfwMQEpUZLxS'
id = '__cc_tuts'

[[instances]]
agent = 'hc-run-agent'
dna = '__cc_tuts'
id = '__cc_tuts'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = false
choose_free_port = false
id = 'cc_tuts_ui'

[[interfaces.instances]]
alias = 'test-instance'
id = '__cc_tuts'

[interfaces.driver]
port = 50001
type = 'websocket'

[[ui_bundles]]
id = 'cc_tuts_ui'
root_dir = '../gui'

[[ui_interfaces]]
bind_address = '127.0.0.1'
bundle = 'cc_tuts_ui'
dna_interface = 'cc_tuts_ui'
id = 'cc_tuts_ui'
port = 8889
reroute_to_root = false

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
